import Foundation

extension QuestionBank {
    static let quantitativeQuestions: [GREQuestion] = [
        // Easy
        comparison("qe-001", .easy, stimulus: "x > 0", quantityA: "x²", quantityB: "x", correct: 3,
            explanation: "If 0 < x < 1, then x² < x; if x > 1, then x² > x. The relationship cannot be determined.", area: "Algebra"),
        numeric("qe-002", .easy, prompt: "What is 3/5 of 40?", answers: ["24"],
            explanation: "(3/5) × 40 = 24.", area: "Arithmetic"),
        single("qe-003", .quantitative, .easy,
            prompt: "A price increases from $80 to $100. What is the percent increase?",
            choices: ["20%", "25%", "40%", "80%", "125%"], correct: 1,
            explanation: "The increase is 20, and 20/80 = 0.25 = 25%.", area: "Arithmetic"),
        numeric("qe-004", .easy, prompt: "What is the median of 3, 5, 7, 8, and 12?", answers: ["7"],
            explanation: "The ordered list has five values, so the middle value is 7.", area: "Data Analysis"),
        numeric("qe-005", .easy, prompt: "A rectangle has perimeter 30 and width 6. What is its area?", answers: ["54"],
            explanation: "2(L + 6) = 30, so L = 9 and the area is 9 × 6 = 54.", area: "Geometry"),
        numeric("qe-006", .easy, prompt: "A bag contains 3 red marbles and 2 blue marbles. If one marble is selected at random, what is the probability that it is red? Enter a decimal or fraction.", answers: ["0.6", ".6", "3/5"],
            explanation: "There are 3 favorable outcomes among 5 equally likely outcomes, so the probability is 3/5 = 0.6.", area: "Data Analysis"),
        numeric("qe-007", .easy, prompt: "If 2x + 5 = 17, what is the value of x?", answers: ["6"],
            explanation: "Subtract 5 and divide by 2: x = 6.", area: "Algebra"),
        comparison("qe-008", .easy, stimulus: "n is a positive integer.", quantityA: "n + 1", quantityB: "n", correct: 0,
            explanation: "Adding 1 to any number makes it greater.", area: "Arithmetic"),
        numeric("qe-009", .easy, prompt: "What is the arithmetic mean of 12, 15, and 18?", answers: ["15"],
            explanation: "(12 + 15 + 18) / 3 = 45/3 = 15.", area: "Data Analysis"),
        numeric("qe-010", .easy, prompt: "The ratio of red pens to blue pens is 2 to 3. If there are 25 pens in all, how many are red?", answers: ["10"],
            explanation: "The 5 ratio parts represent 25 pens, so each part is 5 and red pens = 2 × 5 = 10.", area: "Arithmetic"),
        single("qe-011", .quantitative, .easy,
            prompt: "What is the area of a circle with radius 3?",
            choices: ["3π", "6π", "9π", "12π", "18π"], correct: 2,
            explanation: "Area = πr² = π(3²) = 9π.", area: "Geometry"),
        numeric("qe-012", .easy, prompt: "How many positive multiples of 4 are less than or equal to 20?", answers: ["5"],
            explanation: "They are 4, 8, 12, 16, and 20.", area: "Arithmetic"),
        numeric("qe-013", .easy, prompt: "What is the slope of the line through (1, 2) and (5, 10)?", answers: ["2"],
            explanation: "Slope = (10 − 2)/(5 − 1) = 8/4 = 2.", area: "Algebra"),
        comparison("qe-014", .easy, quantityA: "√49", quantityB: "7", correct: 2,
            explanation: "The principal square root of 49 is 7, so the quantities are equal.", area: "Arithmetic"),
        numeric("qe-015", .easy, prompt: "What is 15 percent of 240?", answers: ["36"],
            explanation: "0.15 × 240 = 36.", area: "Arithmetic"),

        // Medium
        comparison("qm-001", .medium, stimulus: "x² = 16", quantityA: "x", quantityB: "0", correct: 3,
            explanation: "x can be 4 or −4, so Quantity A may be greater or less than Quantity B.", area: "Algebra"),
        numeric("qm-002", .medium, prompt: "If 2x + y = 11 and x − y = 1, what is the value of x?", answers: ["4"],
            explanation: "Adding the equations gives 3x = 12, so x = 4.", area: "Algebra"),
        numeric("qm-003", .medium, prompt: "A fair coin is tossed twice. What is the probability that both tosses are heads? Enter a decimal or fraction.", answers: ["0.25", ".25", "1/4"],
            explanation: "The probability is (1/2)(1/2) = 1/4.", area: "Data Analysis"),
        numeric("qm-004", .medium, prompt: "An account containing $500 grows by 10 percent in each of two consecutive years. What is the balance after the second year?", answers: ["605", "605.0", "605.00"],
            explanation: "Compound growth gives 500(1.10)² = 605.", area: "Arithmetic"),
        numeric("qm-005", .medium, prompt: "A right triangle has legs of lengths 6 and 8. What is its area?", answers: ["24"],
            explanation: "Area = (1/2)(6)(8) = 24.", area: "Geometry"),
        single("qm-006", .quantitative, .medium,
            stimulus: "The five daily customer counts at a shop were 42, 55, 38, 60, and 55.",
            prompt: "Which statement is true?",
            choices: [
                "The mean is 50 and the median is 55.",
                "The mean is 55 and the median is 50.",
                "The mean and median are both 50.",
                "The mean and median are both 55.",
                "The mean is 52 and the median is 50."
            ], correct: 0,
            explanation: "The sum is 250, so the mean is 50. Ordered values are 38, 42, 55, 55, 60, giving median 55.", area: "Data Analysis"),
        numeric("qm-007", .medium, prompt: "Five distinct books are arranged on a shelf. How many different arrangements are possible?", answers: ["120"],
            explanation: "There are 5! = 5 × 4 × 3 × 2 × 1 = 120 arrangements.", area: "Data Analysis"),
        numeric("qm-008", .medium, prompt: "A class of 10 students has an average score of 78. A second class of 15 students has an average score of 88. What is the average score for all 25 students?", answers: ["84"],
            explanation: "The weighted mean is (10×78 + 15×88)/25 = 2100/25 = 84.", area: "Data Analysis"),
        comparison("qm-009", .medium,
            stimulus: "Set A is 2, 4, 6, 8, 10. Set B is 4, 5, 6, 7, 8.",
            quantityA: "The mean of Set A", quantityB: "The median of Set B", correct: 2,
            explanation: "Set A has mean 6, and Set B has median 6.", area: "Data Analysis"),
        numeric("qm-010", .medium, prompt: "The line y = 3x − 7 crosses the x-axis at (a, 0). What is a? Enter a fraction or decimal.", answers: ["7/3", "2.3333333333", "2.333333", "2.33"],
            explanation: "Set y = 0: 3a − 7 = 0, so a = 7/3.", area: "Algebra"),
        multiple("qm-011", .quantitative, .medium,
            prompt: "Which of the following are prime factors of 84? Select all that apply.",
            choices: ["2", "3", "5", "7", "11"], correct: [0, 1, 3], maximum: 5,
            explanation: "84 = 2² × 3 × 7, so its prime factors are 2, 3, and 7.", area: "Arithmetic"),
        comparison("qm-012", .medium,
            stimulus: "List Q is formed by adding 10 to every number in list P.",
            quantityA: "The standard deviation of list P", quantityB: "The standard deviation of list Q", correct: 2,
            explanation: "Adding the same constant shifts every value but does not change the spread.", area: "Data Analysis"),
        numeric("qm-013", .medium, prompt: "Pipe A fills a tank in 6 hours and Pipe B fills the same tank in 3 hours. At their constant rates, how many hours do they take working together?", answers: ["2", "2.0"],
            explanation: "Their combined rate is 1/6 + 1/3 = 1/2 tank per hour, so they need 2 hours.", area: "Arithmetic"),
        numeric("qm-014", .medium, prompt: "A $200 jacket is discounted 20 percent. The discounted price is then increased by 25 percent. What is the final price in dollars?", answers: ["200", "200.0", "200.00"],
            explanation: "200(0.80)(1.25) = 200; the percentage changes use different bases but cancel here.", area: "Arithmetic"),
        multiple("qm-015", .quantitative, .medium,
            prompt: "If −2 < x ≤ 3, which values could equal x? Select all that apply.",
            choices: ["−3", "−2", "0", "3", "4"], correct: [2, 3], maximum: 5,
            explanation: "The interval excludes −2 and includes 3, so 0 and 3 are possible.", area: "Algebra"),

        // Hard
        numeric("qh-001", .hard, prompt: "Three fair coins are tossed. What is the probability of getting exactly two heads? Enter a decimal or fraction.", answers: ["3/8", "0.375", ".375"],
            explanation: "There are C(3,2) = 3 favorable outcomes among 2³ = 8 equally likely outcomes.", area: "Data Analysis"),
        single("qh-002", .quantitative, .hard,
            prompt: "If the two roots of x² − 7x + k = 0 differ by 1, what is k?",
            choices: ["10", "11", "12", "13", "14"], correct: 2,
            explanation: "The roots have sum 7 and differ by 1, so they are 3 and 4. Their product k is 12.", area: "Algebra"),
        numeric("qh-003", .hard, prompt: "In a group of 80 people, 52 speak French, 38 speak Spanish, and 12 speak neither language. How many speak both French and Spanish?", answers: ["22"],
            explanation: "68 speak at least one language. By inclusion-exclusion, 52 + 38 − both = 68, so both = 22.", area: "Data Analysis"),
        numeric("qh-004", .hard, prompt: "A car travels 60 miles at 30 miles per hour and then 60 miles at 60 miles per hour. What is its average speed for the entire trip, in miles per hour?", answers: ["40", "40.0"],
            explanation: "The trip takes 2 + 1 = 3 hours and covers 120 miles, so average speed is 40 mph.", area: "Arithmetic"),
        comparison("qh-005", .hard,
            stimulus: "n is an integer and n² is divisible by 12.",
            quantityA: "n", quantityB: "6", correct: 3,
            explanation: "n must be divisible by 6, but it may be …, −6, 0, 6, 12, …; the relationship varies.", area: "Arithmetic"),
        multiple("qh-006", .quantitative, .hard,
            stimulus: "A dataset contains 2, 4, 4, 7, 8, 8, 8, and 15.",
            prompt: "Which statements are true? Select all that apply.",
            choices: [
                "The median is 7.5.",
                "The mode is 8.",
                "The range is 11.",
                "The mean is greater than the median."
            ], correct: [0, 1], maximum: 4,
            explanation: "Median = (7+8)/2 = 7.5, mode = 8, range = 13, and mean = 56/8 = 7, which is not greater than the median. Therefore only the first two statements are true.", area: "Data Analysis"),
        numeric("qh-007", .hard, prompt: "A square is inscribed in a circle of radius 5. What is the area of the square?", answers: ["50"],
            explanation: "The square's diagonal is the circle's diameter, 10. Since d² = 2s², the area s² = 100/2 = 50.", area: "Geometry"),
        numeric("qh-008", .hard, prompt: "A sequence is defined by a₁ = 2 and aₙ = 2aₙ₋₁ + 1 for n > 1. What is a₅?", answers: ["47"],
            explanation: "The terms are 2, 5, 11, 23, 47.", area: "Algebra"),
        numeric("qh-009", .hard, prompt: "A positive integer leaves remainder 3 when divided by 5. What remainder does three times the integer leave when divided by 5?", answers: ["4"],
            explanation: "If n ≡ 3 (mod 5), then 3n ≡ 9 ≡ 4 (mod 5).", area: "Arithmetic"),
        numeric("qh-010", .hard, prompt: "A mixture contains 30 liters of a 20 percent salt solution. How many liters of pure water must be added to make the mixture 12 percent salt?", answers: ["20"],
            explanation: "The mixture contains 6 liters of salt. For that to be 12%, total volume must be 6/0.12 = 50 liters, requiring 20 liters of water.", area: "Arithmetic"),
        single("qh-011", .quantitative, .hard,
            prompt: "If x and y are positive integers and 3x + 5y = 31, what is the greatest possible value of x?",
            choices: ["2", "3", "4", "7", "8"], correct: 3,
            explanation: "Testing positive y values modulo 3 gives y = 2 and x = 7; larger x would require y < 2 and gives no positive integer solution.", area: "Algebra"),
        single("qh-012", .quantitative, .hard,
            prompt: "For f(x) = x² − 2x, which expression is equal to f(a + 1) − f(a)?",
            choices: ["2a − 3", "2a − 1", "2a + 1", "a² − 1", "a² + 2a − 1"], correct: 1,
            explanation: "f(a+1) = (a+1)² − 2(a+1) = a² − 1. Subtracting a² − 2a gives 2a − 1.", area: "Algebra"),
        numeric("qh-013", .hard, prompt: "A box contains 4 green and 6 white balls. Two balls are drawn without replacement. Given that the first ball is green, what is the probability that the second is white? Enter a decimal or fraction.", answers: ["2/3", "0.6666666667", ".6666666667", "0.667", ".667"],
            explanation: "After a green ball is removed, 6 of the 9 remaining balls are white, so the conditional probability is 6/9 = 2/3.", area: "Data Analysis"),
        numeric("qh-014", .hard, prompt: "A rectangular field measures 0.3 kilometer by 250 meters. What is its area in square meters?", answers: ["75000", "75,000"],
            explanation: "0.3 kilometer = 300 meters, and 300 × 250 = 75,000 square meters.", area: "Geometry"),
        comparison("qh-015", .hard,
            stimulus: "Set S consists of five distinct positive integers with median 10.",
            quantityA: "The mean of S", quantityB: "10", correct: 3,
            explanation: "For {1,2,10,11,12}, the mean is below 10; for {8,9,10,50,60}, it is above 10. The relationship cannot be determined.", area: "Data Analysis")
    ]
}
