import Foundation

extension QuestionBank {
    static let verbalQuestions: [GREQuestion] = [
        // Easy
        completion("ve-001", .easy,
            prompt: "Although the biographer admired her subject, she was not _____; the book discusses his failures as candidly as his triumphs.",
            columns: [["obsequious", "uncritical", "indifferent"]], correct: [1],
            explanation: "The contrast after “Although” and the candid discussion of failures show that the author was not uncritical."),
        completion("ve-002", .easy,
            prompt: "The committee's final report was surprisingly _____: it stated its recommendation in two pages and omitted every unnecessary detail.",
            columns: [["concise", "ambiguous", "derivative"]], correct: [0],
            explanation: "A two-page report without unnecessary detail is concise."),
        completion("ve-003", .easy,
            prompt: "Because the evidence was merely anecdotal, the researcher treated the striking claim with _____.",
            columns: [["skepticism", "reverence", "complacency"]], correct: [0],
            explanation: "Weak anecdotal evidence warrants skepticism."),
        completion("ve-004", .easy,
            prompt: "The mayor's apology did little to _____ the residents, who remained angry about the sudden closure.",
            columns: [["appease", "provoke", "bewilder"]], correct: [0],
            explanation: "The residents remained angry, so the apology failed to appease, or calm, them."),
        completion("ve-005", .easy,
            prompt: "Far from being _____, the lecturer welcomed interruptions and adjusted the discussion whenever students raised an objection.",
            columns: [["dogmatic", "lucid", "amiable"]], correct: [0],
            explanation: "Welcoming objections is the opposite of being dogmatic."),
        completion("ve-006", .easy,
            prompt: "The museum's new labels make the collection more _____ to visitors who lack specialized training.",
            columns: [["accessible", "esoteric", "redundant"]], correct: [0],
            explanation: "Clear labels make a specialized collection easier to understand, or accessible."),
        equivalence("ve-007", .easy,
            prompt: "The editor asked the author to _____ several claims that rested on outdated data.",
            choices: ["retract", "circulate", "withdraw", "embellish", "catalog", "vindicate"], correct: [0, 2],
            explanation: "Retract and withdraw both mean to take back a claim."),
        equivalence("ve-008", .easy,
            prompt: "Even after the long hike, Mira remained remarkably _____ and proposed exploring another trail.",
            choices: ["vigorous", "weary", "energetic", "sullen", "cautious", "perplexed"], correct: [0, 2],
            explanation: "Vigorous and energetic both fit her readiness for another trail."),
        equivalence("ve-009", .easy,
            prompt: "The instructions were so _____ that every participant completed the task without asking a question.",
            choices: ["lucid", "terse", "clear", "novel", "rigid", "subtle"], correct: [0, 2],
            explanation: "Lucid and clear explain why nobody needed clarification."),
        equivalence("ve-010", .easy,
            prompt: "The critic found the plot utterly _____; she predicted the ending after the opening scene.",
            choices: ["credible", "predictable", "conventional", "absorbing", "erratic", "intricate"], correct: [1, 2],
            explanation: "Predictable and conventional both support the ability to foresee the ending."),
        equivalence("ve-011", .easy,
            prompt: "Rather than _____ the disagreement, the new evidence settled it decisively.",
            choices: ["resolve", "prolong", "extend", "expose", "clarify", "conceal"], correct: [1, 2],
            explanation: "Prolong and extend are equivalent and contrast with settling the disagreement."),
        single("ve-012", .verbal, .easy,
            stimulus: "City planners often plant many species along a single street, assuming that variety protects the urban canopy from disease. Variety helps only when the selected trees differ in susceptibility. Ten cultivars that share the same vulnerability provide less protection than three genuinely resistant species.",
            prompt: "Which choice best states the main point of the passage?",
            choices: [
                "Urban streets should contain exactly three tree species.",
                "The number of tree varieties matters more than their disease resistance.",
                "Effective biological diversity depends on meaningful differences, not labels alone.",
                "Most cultivars are more resistant than naturally occurring species.",
                "City planners should avoid planting trees along a single street."
            ], correct: 2,
            explanation: "The passage distinguishes nominal variety from diversity that actually changes disease susceptibility.", area: "Reading Comprehension"),
        single("ve-013", .verbal, .easy,
            stimulus: "City planners often plant many species along a single street, assuming that variety protects the urban canopy from disease. Variety helps only when the selected trees differ in susceptibility. Ten cultivars that share the same vulnerability provide less protection than three genuinely resistant species.",
            prompt: "The comparison in the final sentence primarily serves to",
            choices: [
                "illustrate the difference between nominal and functional diversity",
                "prove that cultivars are never useful",
                "show that urban diseases attack only common trees",
                "question whether resistance can be measured",
                "recommend a universal planting ratio"
            ], correct: 0,
            explanation: "The numerical contrast illustrates that labels or counts do not guarantee functional resistance.", area: "Reading Comprehension"),
        single("ve-014", .verbal, .easy,
            stimulus: "Early recordings captured only a narrow range of sound, yet listeners do not always judge them as inferior. The hiss and distortion can signal historical distance, leading audiences to attend to performance rather than fidelity.",
            prompt: "The passage suggests that imperfections in early recordings can",
            choices: [
                "prevent audiences from identifying the performer",
                "increase appreciation by shaping how listeners attend",
                "reproduce a wider range of sound than modern equipment",
                "make fidelity the listener's only concern",
                "eliminate evidence of historical distance"
            ], correct: 1,
            explanation: "The imperfections may redirect attention toward the performance and heighten the historical experience.", area: "Reading Comprehension"),
        single("ve-015", .verbal, .easy,
            stimulus: "Early recordings captured only a narrow range of sound, yet listeners do not always judge them as inferior. The hiss and distortion can signal historical distance, leading audiences to attend to performance rather than fidelity.",
            prompt: "The word “yet” signals a contrast between",
            choices: [
                "technical limitation and perceived value",
                "historical distance and modern equipment",
                "performance and the identity of a performer",
                "hiss and distortion",
                "audiences and recording engineers"
            ], correct: 0,
            explanation: "The recordings are technically limited, but listeners may still value them.", area: "Reading Comprehension"),

        // Medium
        completion("vm-001", .medium,
            prompt: "The scientist's public manner was _____, but her laboratory notes reveal a mind impatient with easy answers.",
            columns: [["combative", "unassuming", "theatrical"]], correct: [1],
            explanation: "“But” contrasts an unassuming public manner with intense private intellectual ambition."),
        completion("vm-002", .medium,
            prompt: "The proposal is not merely _____; because it relies on data from a single unusual year, its conclusion is also _____.",
            columns: [["costly", "premature", "orthodox"], ["tenuous", "inevitable", "comprehensive"]], correct: [1, 0],
            explanation: "One unusual year makes the proposal premature and its conclusion weak, or tenuous."),
        completion("vm-003", .medium,
            prompt: "Paradoxically, the abundance of surviving letters has made the historian's task more _____, for the documents frequently _____ one another.",
            columns: [["straightforward", "arduous", "peripheral"], ["corroborate", "contradict", "duplicate"]], correct: [1, 1],
            explanation: "Conflicting documents make the task arduous; “Paradoxically” marks why more evidence does not make it easier."),
        completion("vm-004", .medium,
            prompt: "Her review was _____ without being malicious: each criticism was sharp, but none attacked the author's character.",
            columns: [["incisive", "evasive", "laudatory"]], correct: [0],
            explanation: "Incisive means penetrating or sharply analytical, consistent with strong but fair criticism."),
        completion("vm-005", .medium,
            prompt: "The new translation avoids the _____ diction of its predecessor and instead uses language that sounds deliberately _____.",
            columns: [["stilted", "precise", "colloquial"], ["archaic", "natural", "ornate"]], correct: [0, 1],
            explanation: "Avoiding stiff, stilted diction in favor of natural language forms a coherent contrast."),
        completion("vm-006", .medium,
            prompt: "Since the regulation contains numerous exceptions, its apparent simplicity is _____.",
            columns: [["deceptive", "commendable", "immutable"]], correct: [0],
            explanation: "Many exceptions make the regulation less simple than it appears, so the simplicity is deceptive."),
        equivalence("vm-007", .medium,
            prompt: "The chair's attempt to _____ the dispute failed when both sides interpreted her neutral statement as an insult.",
            choices: ["mediate", "intensify", "arbitrate", "document", "evade", "publicize"], correct: [0, 2],
            explanation: "Mediate and arbitrate both mean to intervene to settle a dispute."),
        equivalence("vm-008", .medium,
            prompt: "Because the manuscript offered no evidence for its most dramatic assertion, reviewers called that assertion _____.",
            choices: ["conjectural", "methodical", "speculative", "orthodox", "lucid", "exhaustive"], correct: [0, 2],
            explanation: "Conjectural and speculative both describe a claim not supported by evidence."),
        equivalence("vm-009", .medium,
            prompt: "The comedian's seemingly casual monologue was actually _____, with every pause rehearsed.",
            choices: ["spontaneous", "meticulous", "improvised", "calculated", "rambling", "opaque"], correct: [1, 3],
            explanation: "Meticulous and calculated capture the monologue's carefully planned character."),
        equivalence("vm-010", .medium,
            prompt: "The ambassador's response was deliberately _____, permitting both governments to claim that she supported their position.",
            choices: ["unequivocal", "ambiguous", "equivocal", "conciliatory", "blunt", "inflammatory"], correct: [1, 2],
            explanation: "Ambiguous and equivocal both allow more than one interpretation."),
        equivalence("vm-011", .medium,
            prompt: "Years of repetition had made the once-radical slogan seem _____.",
            choices: ["hackneyed", "subversive", "trite", "cryptic", "prescient", "volatile"], correct: [0, 2],
            explanation: "Hackneyed and trite both mean overused and no longer fresh."),
        single("vm-012", .verbal, .medium,
            stimulus: "Some economists treat household repairs performed by residents as invisible because no money changes hands. This convention keeps national accounts comparable, but it also means that two households performing the same repair can appear to produce different amounts if one hires a contractor and the other does not.",
            prompt: "The author mentions two households primarily to",
            choices: [
                "argue that residents repair homes better than contractors",
                "illustrate a distortion created by a useful accounting convention",
                "show that national accounts cannot be compared",
                "explain why all unpaid work should receive a fixed price",
                "deny that household repairs have economic value"
            ], correct: 1,
            explanation: "The example exposes a limitation of a convention that otherwise supports comparability.", area: "Reading Comprehension"),
        multiple("vm-013", .verbal, .medium,
            stimulus: "Some economists treat household repairs performed by residents as invisible because no money changes hands. This convention keeps national accounts comparable, but it also means that two households performing the same repair can appear to produce different amounts if one hires a contractor and the other does not.",
            prompt: "Which statements are supported by the passage? Select all that apply.",
            choices: [
                "National accounting conventions can omit economically useful activity.",
                "Hiring a contractor always increases a household's actual productivity.",
                "A rule can aid comparison while introducing a misleading difference."
            ], correct: [0, 2], maximum: 3,
            explanation: "Unpaid repairs are omitted, and the same convention both aids comparison and creates an apparent difference.", area: "Reading Comprehension"),
        single("vm-014", .verbal, .medium,
            stimulus: "Biologists once inferred that an island bird was nocturnal because museum specimens had unusually large eyes. Field observations later showed daytime activity. The large eyes, it turned out, helped the bird forage beneath a dim forest canopy rather than after sunset.",
            prompt: "The field observations challenged the earlier inference by showing that",
            choices: [
                "museum specimens had been mislabeled",
                "large eyes can be adaptive in more than one lighting context",
                "the forest canopy was brighter at night",
                "the bird's eye size varied seasonally",
                "nocturnal birds generally have small eyes"
            ], correct: 1,
            explanation: "Large eyes were correctly observed but incorrectly treated as uniquely indicating nocturnal activity.", area: "Reading Comprehension"),
        single("vm-015", .verbal, .medium,
            stimulus: "Biologists once inferred that an island bird was nocturnal because museum specimens had unusually large eyes. Field observations later showed daytime activity. The large eyes, it turned out, helped the bird forage beneath a dim forest canopy rather than after sunset.",
            prompt: "Which description best characterizes the passage's structure?",
            choices: [
                "A disputed theory is defended with new laboratory data.",
                "A general rule is stated and then applied to two species.",
                "An initial interpretation is revised after a new kind of evidence appears.",
                "Two equally plausible explanations remain unresolved.",
                "A field observation is rejected because of a specimen."
            ], correct: 2,
            explanation: "A specimen-based inference is corrected by field observation and reinterpreted.", area: "Reading Comprehension"),

        // Hard
        completion("vh-001", .hard,
            prompt: "The philosopher's reputation for _____ is puzzling: although her prose is dense, her arguments rarely permit more than one interpretation.",
            columns: [["obscurity", "equivocation", "precision"]], correct: [0],
            explanation: "Dense prose may create a reputation for obscurity, but unambiguous arguments make that reputation puzzling."),
        completion("vh-002", .hard,
            prompt: "Far from _____ the prevailing theory, the anomalous result initially seemed to _____ it, since researchers mistook a measurement error for confirmation.",
            columns: [["undermining", "clarifying", "anticipating"], ["repudiate", "vindicate", "complicate"]], correct: [0, 1],
            explanation: "“Far from” sets up the contrast: a result that could undermine the theory appeared to vindicate it."),
        completion("vh-003", .hard,
            prompt: "The archive is simultaneously _____ and _____: its catalog is exemplary, but access restrictions make much of the collection unusable.",
            columns: [["orderly", "negligible", "derivative"], ["invaluable", "intractable", "comprehensive"]], correct: [0, 1],
            explanation: "An exemplary catalog makes it orderly; severe restrictions make it intractable for researchers."),
        completion("vh-004", .hard,
            prompt: "What appears to be the critic's _____ is actually a calculated restraint; by understating her objections, she makes them more _____.",
            columns: [["diffidence", "vehemence", "caprice"], ["diffuse", "telling", "orthodox"]], correct: [0, 1],
            explanation: "Apparent diffidence can be deliberate understatement that makes criticism especially telling."),
        completion("vh-005", .hard,
            prompt: "The study's conclusion is _____ rather than definitive: it is _____ by a small sample and by the absence of a control group.",
            columns: [["provisional", "redundant", "incontrovertible"], ["bolstered", "circumscribed", "disseminated"]], correct: [0, 1],
            explanation: "Methodological limits circumscribe the claim, making it provisional."),
        completion("vh-006", .hard,
            prompt: "Because the novelist refuses to explain her symbols, interpretations proliferate; her silence is less an act of _____ than a source of productive _____.",
            columns: [["reticence", "candor", "didacticism"], ["ambiguity", "consensus", "banality"]], correct: [2, 0],
            explanation: "Refusing to teach a fixed meaning rejects didacticism and sustains productive ambiguity."),
        equivalence("vh-007", .hard,
            prompt: "The apparent consensus was _____: once the chair requested specific commitments, the coalition immediately dissolved.",
            choices: ["durable", "illusory", "specious", "unanimous", "pragmatic", "fortuitous"], correct: [1, 2],
            explanation: "Illusory and specious both indicate that the apparent agreement was not genuine."),
        equivalence("vh-008", .hard,
            prompt: "By presenting a radical proposal in the language of routine maintenance, the report sought to _____ its implications.",
            choices: ["accentuate", "obscure", "vindicate", "camouflage", "enumerate", "repudiate"], correct: [1, 3],
            explanation: "Obscure and camouflage both mean to conceal the proposal's radical implications."),
        equivalence("vh-009", .hard,
            prompt: "The scholar is not known for intellectual _____; she abandons even cherished hypotheses when contrary evidence appears.",
            choices: ["probity", "tenacity", "obstinacy", "acuity", "diffidence", "caprice"], correct: [1, 2],
            explanation: "Tenacity and obstinacy both denote persistence, which the scholar does not display toward disproven ideas."),
        equivalence("vh-010", .hard,
            prompt: "Although the essay mimics the vocabulary of scientific objectivity, its argument is plainly _____.",
            choices: ["disinterested", "tendentious", "partisan", "empirical", "methodical", "inchoate"], correct: [1, 2],
            explanation: "Tendentious and partisan both describe an argument shaped by a particular agenda."),
        equivalence("vh-011", .hard,
            prompt: "The treaty's language was intentionally _____, postponing rather than resolving the central dispute.",
            choices: ["perspicuous", "indeterminate", "categorical", "equivocal", "prescriptive", "trenchant"], correct: [1, 3],
            explanation: "Indeterminate and equivocal describe language that leaves the issue unsettled."),
        single("vh-012", .verbal, .hard,
            stimulus: "Historians of technology often call a device successful when later machines inherit its design. Such genealogical judgments, however, can mistake influence for fitness. A technically awkward machine may become a template because its maker controlled a market, while a more effective rival leaves no descendants. Design lineage therefore records the circumstances of diffusion as much as engineering merit.",
            prompt: "The author would most likely agree that",
            choices: [
                "later adoption reliably identifies the technically superior design",
                "market power can affect which designs appear historically successful",
                "technically awkward machines rarely influence later designs",
                "engineering merit has no effect on the diffusion of technology",
                "historians should study only devices with living descendants"
            ], correct: 1,
            explanation: "The passage explicitly uses market control to show why lineage can diverge from technical fitness.", area: "Reading Comprehension"),
        multiple("vh-013", .verbal, .hard,
            stimulus: "Historians of technology often call a device successful when later machines inherit its design. Such genealogical judgments, however, can mistake influence for fitness. A technically awkward machine may become a template because its maker controlled a market, while a more effective rival leaves no descendants. Design lineage therefore records the circumstances of diffusion as much as engineering merit.",
            prompt: "Which functions does the example of the awkward machine serve? Select all that apply.",
            choices: [
                "It provides a mechanism by which influence and technical merit can diverge.",
                "It proves that market control always defeats better engineering.",
                "It supports the qualification of genealogical judgments.",
                "It establishes that descendants never resemble their templates."
            ], correct: [0, 2], maximum: 4,
            explanation: "The example explains a possible divergence and supports the author's caution; it does not claim this always occurs.", area: "Reading Comprehension"),
        single("vh-014", .verbal, .hard,
            stimulus: "A map is conventionally praised for suppressing irrelevant detail. Yet relevance is not inherent in terrain; it is assigned by a map's purpose. A subway diagram that distorts distance may be excellent for navigation and useless for estimating walking time. Calls for a perfectly neutral map therefore conceal a prior choice about what the map should enable its reader to do.",
            prompt: "The passage's central claim is that mapmaking",
            choices: [
                "should always preserve physical distance",
                "cannot be evaluated apart from the purposes that determine relevance",
                "is neutral when it removes enough geographic detail",
                "is less useful for navigation than for estimating walking time",
                "becomes accurate only when distortions are clearly labeled"
            ], correct: 1,
            explanation: "The author argues that relevance and quality depend on a map's intended use." , area: "Reading Comprehension"),
        single("vh-015", .verbal, .hard,
            stimulus: "A map is conventionally praised for suppressing irrelevant detail. Yet relevance is not inherent in terrain; it is assigned by a map's purpose. A subway diagram that distorts distance may be excellent for navigation and useless for estimating walking time. Calls for a perfectly neutral map therefore conceal a prior choice about what the map should enable its reader to do.",
            prompt: "The subway diagram is introduced as an example of an object that",
            choices: [
                "fails by every reasonable standard of accuracy",
                "contains more detail than its users require",
                "can be judged differently under different practical aims",
                "conceals its purpose from readers",
                "represents terrain without assigning relevance"
            ], correct: 2,
            explanation: "It is good for one task and poor for another, showing that evaluation depends on purpose.", area: "Reading Comprehension")
    ]
}
