#!/usr/bin/env python3
"""Import the user-authorized 2026-07-20 part-two GRE collection.

The importer is intentionally conservative. It only emits questions whose
passage, prompt, complete options, and answer key can be paired without
guessing. The source PDFs remain outside the repository; the app bundles only
normalized JSON records and an audit manifest.
"""

from __future__ import annotations

import argparse
import copy
import difflib
import json
import re
import sys
from collections import Counter
from pathlib import Path

import pdfplumber

try:
    from opencc import OpenCC
except ImportError as error:  # pragma: no cover - actionable CLI failure
    raise SystemExit(
        "Install opencc-python-reimplemented in the importer environment."
    ) from error


ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "Gre Simulation"
RESOURCES = APP / "Resources"
TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

from enrich_vocabulary import compact_translation, enrich_vocabulary_entries, load_ecdict


TAIWAN = OpenCC("s2twp")
PART2_QUESTION_SOURCE = "2026-07-20 Part 2 authorized collection"
RC36_SOURCE = "新 GRE 閱讀理解 36 套 · 授權內容"
READ300_SOURCE = "GRE 閱讀 300 篇 · 授權內容"
GRUBER_QUESTION_SOURCE = "Gruber's Complete GRE Guide · authorized copy"
GRUBER_VOCAB_SOURCE = "Gruber's Complete GRE Guide · authorized vocabulary"

PAGE_MARKER = re.compile(r"===== PDF PAGE (\d+) =====")
QUESTION_ANCHOR = re.compile(r"(?m)^\s*(\d{1,2})\.\s*(?!\d)(.+)$")
PAREN_OPTION = re.compile(r"(?m)^\s*(?:\(([A-E])\)|[□■○◯●]\s*([A-E])|([A-E])[.．])\s*(.*)$")
PLAIN_OPTION = re.compile(r"(?m)^\s*(?:\(([A-E])\)|([A-E])[.．])\s+(.*)$")
SELECT_ALL_INSTRUCTION = re.compile(
    r"For\s+the\s+following\s+question,?\s+consi\s*der\s+each\s+of\s+the\s+choi\s*ces\s+"
    r"separately\s+and\s+select\s+all\s+that\s+apply\.?",
    re.I,
)
LAYOUT_NOISE = re.compile(
    r"(?:\[?This\s+page\s+(?:is\s+)?intentionally\s+left\s+blank\.?]?|"
    r"GO\s+ON\s+TO\s+THE\s+NEXT\s+PAGE|STOP!?)",
    re.I,
)


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def normalized_space(text: str) -> str:
    text = text.replace("\u00a0", " ").replace("\ufeff", " ")
    text = text.replace("―", "—").replace("‖", '"')
    return re.sub(r"\s+", " ", text).strip()


def normalized_word(word: str) -> str:
    return normalized_space(word).replace("’", "'").lower()


def taiwan_text(text: str) -> str:
    converted = normalized_space(text)
    for _ in range(4):
        next_value = TAIWAN.convert(converted)
        if next_value == converted:
            break
        converted = next_value
    converted = converted.replace("視頻", "影片").replace("信息", "資訊")
    converted = converted.replace("支持哪一項", "支持下列哪一項")
    return converted


def content_signature(question: dict) -> str:
    fields = [question.get("stimulus") or "", question.get("prompt") or ""]
    return re.sub(r"[^a-z0-9]+", "", " ".join(fields).lower())


def prompt_signature(question: dict) -> str:
    return re.sub(r"[^a-z0-9]+", "", (question.get("prompt") or "").lower())


def page_before(text: str, position: int) -> int:
    matches = list(PAGE_MARKER.finditer(text, 0, position))
    return int(matches[-1].group(1)) if matches else 0


def remove_layout_noise(text: str) -> str:
    text = SELECT_ALL_INSTRUCTION.sub(" ", text)
    text = LAYOUT_NOISE.sub(" ", text)
    text = PAGE_MARKER.sub(" ", text)
    lines = []
    for line in text.splitlines():
        compact = normalized_space(line)
        if not compact:
            continue
        if re.fullmatch(r"\d{1,3}", compact):
            continue
        if compact.lower() == "line":
            continue
        if re.search(r"(?:sharewithu|Foxit|Generated by|本文章由|www\.)", compact, re.I):
            continue
        compact = re.sub(r"^Line\s+", "", compact)
        compact = re.sub(r"^(?:Line\s*)?(?:5|10|15|20|25|30|35|40|45|50)\s+", "", compact)
        lines.append(compact)
    cleaned = normalized_space(" ".join(lines))
    cleaned = SELECT_ALL_INSTRUCTION.sub(" ", cleaned)
    cleaned = LAYOUT_NOISE.sub(" ", cleaned)
    cleaned = re.sub(r"\s*[\[\]]\s*$", "", cleaned)
    return normalized_space(cleaned)


def clean_stimulus(text: str) -> str:
    text = re.sub(
        r"(?is)Questions?\s+\d+\s+(?:to|through|–|-)\s+\d+\s+are based on the following reading passage\.?",
        " ",
        text,
    )
    text = SELECT_ALL_INSTRUCTION.sub(" ", text)
    text = re.sub(r"\(\s*\d+\s*words?\s*\)", " ", text, flags=re.I)
    return remove_layout_noise(text)


def clean_prompt(text: str) -> str:
    text = SELECT_ALL_INSTRUCTION.sub(" ", text)
    return remove_layout_noise(text)


def split_standalone_prompt(text: str) -> tuple[str | None, str]:
    """Separate a self-contained argument from its actual question sentence."""
    value = clean_prompt(text)
    if len(value.split()) < 45:
        return None, value

    # Some logical-reasoning items print the question first and the argument second.
    initial = re.match(r"^(.{20,180}?\?)\s+(.+)$", value)
    if initial and len(initial.group(2).split()) >= 25 and not re.match(
        r"^(?:I|II|III|IV)\s*[.．]", initial.group(2)
    ):
        return initial.group(2).strip(), initial.group(1).strip()

    # Others print the argument first, followed by a standard question cue.
    cue = re.compile(
        r"(?i)(?<!^)\b(?:Which\s+of\s+the\s+following|The\s+statements?\s+above|"
        r"If\s+the\s+statements?\s+(?:above\s+)?(?:are|given\s+are)\s+true|"
        r"The\s+information\s+above|The\s+passage\s+above)\b"
    )
    matches = list(cue.finditer(value))
    for marker in matches:
        stimulus = value[: marker.start()].strip()
        prompt = value[marker.start() :].strip()
        if len(stimulus.split()) >= 25 and len(prompt.split()) >= 6:
            return stimulus, prompt
    return None, value


def split_after_final_option(text: str) -> tuple[str, str]:
    separators = list(re.finditer(r"\n(?:[ \t]*\n){2,}", text))
    for separator in separators:
        before = text[: separator.start()]
        after = text[separator.end() :]
        if len(remove_layout_noise(before).split()) >= 1 and len(clean_stimulus(after).split()) >= 12:
            return before, after
    page = PAGE_MARKER.search(text)
    if page and len(clean_stimulus(text[page.start() :]).split()) >= 12:
        return text[: page.start()], text[page.start() :]
    return text, ""


def parse_options(segment: str, pattern: re.Pattern) -> tuple[str, dict[str, str], str]:
    matches = list(pattern.finditer(segment))
    if not matches:
        return clean_prompt(segment), {}, ""
    options: dict[str, str] = {}
    trailing = ""
    for index, match in enumerate(matches):
        letter = next(group for group in match.groups()[:-1] if group is not None)
        start = match.start(match.lastindex) if match.lastindex else match.end()
        # The option text is the pattern's final capture followed by wrapped lines.
        first = match.groups()[-1]
        end = matches[index + 1].start() if index + 1 < len(matches) else len(segment)
        raw = first + segment[match.end() : end]
        if index == len(matches) - 1:
            raw, trailing = split_after_final_option(raw)
        options[letter] = remove_layout_noise(raw)
    return clean_prompt(segment[: matches[0].start()]), options, trailing


def contiguous_options(options: dict[str, str]) -> bool:
    expected = list("ABCDE"[: len(options)])
    return list(sorted(options)) == expected and len(options) in {3, 5, 6}


def answer_explanation(answer: str, options: dict[str, str], detailed: str = "") -> str:
    keyed = "、".join(f"{letter}（{options[letter]}）" for letter in answer if letter in options)
    prefix = f"正確答案為 {keyed}。"
    detail = taiwan_text(detailed)
    detail = re.sub(r"\bBy\s+Desperado\b", "", detail, flags=re.I)
    detail = re.sub(r"(?:分享|轉載|製作)\S{0,20}", "", detail)
    detail = normalized_space(detail)
    if len(detail) >= 20:
        return (prefix + detail)[:1800]
    return prefix + "請依文章中的明示資訊、語意關係、作者立場或合理推論，逐一核對各選項。"


def make_reading_question(
    qid: str,
    difficulty: str,
    stimulus: str,
    prompt: str,
    options: dict[str, str],
    answer: str,
    explanation: str,
    source_title: str,
    source_detail: str,
) -> dict | None:
    if not contiguous_options(options):
        return None
    letters = list("ABCDE"[: len(options)])
    if not answer or any(letter not in options for letter in answer):
        return None
    if len(stimulus.split()) < 18 or len(prompt.split()) < 4:
        return None
    if any(not value or len(value) > 500 for value in options.values()):
        return None
    maximum = len(answer) if len(answer) > 1 else 1
    return {
        "id": qid,
        "measure": "verbal",
        "difficulty": difficulty,
        "format": "multipleChoice" if maximum > 1 else "singleChoice",
        "stimulus": stimulus,
        "prompt": prompt,
        "quantityA": None,
        "quantityB": None,
        "groups": [{
            "id": "main",
            "title": None,
            "options": [{"id": f"o{index}", "text": options[letter]} for index, letter in enumerate(letters)],
            "maximumSelections": maximum,
        }],
        "correctSelections": {"main": [f"o{letters.index(letter)}" for letter in answer]},
        "acceptedNumericAnswers": [],
        "explanation": explanation,
        "contentArea": "Reading Comprehension",
        "source": {
            "title": source_title,
            "detail": source_detail,
            "isAuthorizedSourceItem": True,
        },
    }


class DuplicateIndex:
    def __init__(self, existing: list[dict]):
        self.signatures = {content_signature(question) for question in existing}
        self.prompts: dict[str, list[dict]] = {}
        for question in existing:
            tokens = re.findall(r"[a-z]+", (question.get("prompt") or "").lower())[:7]
            if tokens:
                self.prompts.setdefault(" ".join(tokens), []).append(question)

    def is_duplicate(self, question: dict) -> bool:
        signature = content_signature(question)
        if signature in self.signatures:
            return True
        tokens = re.findall(r"[a-z]+", (question.get("prompt") or "").lower())[:7]
        candidates = self.prompts.get(" ".join(tokens), [])
        prompt = prompt_signature(question)
        stimulus = re.sub(r"[^a-z0-9]+", "", (question.get("stimulus") or "").lower())[:1500]
        for candidate in candidates:
            other_prompt = prompt_signature(candidate)
            other_stimulus = re.sub(r"[^a-z0-9]+", "", (candidate.get("stimulus") or "").lower())[:1500]
            if difflib.SequenceMatcher(None, prompt, other_prompt).ratio() >= 0.96 and difflib.SequenceMatcher(
                None, stimulus, other_stimulus
            ).ratio() >= 0.93:
                return True
        return False

    def add(self, question: dict) -> None:
        self.signatures.add(content_signature(question))
        tokens = re.findall(r"[a-z]+", (question.get("prompt") or "").lower())[:7]
        if tokens:
            self.prompts.setdefault(" ".join(tokens), []).append(question)


def split_numbered_sections(text: str, heading: re.Pattern) -> dict[int, str]:
    matches = list(heading.finditer(text))
    sections = {}
    for index, match in enumerate(matches):
        number = int(match.group(1))
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        sections[number] = text[match.end() : end]
    return sections


def sequential_anchors(text: str, maximum: int = 30) -> list[re.Match]:
    anchors: list[re.Match] = []
    position = 0
    expected = 1
    while expected <= maximum:
        pattern = re.compile(rf"(?m)^\s*{expected}\.\s*(?!\d)")
        absolute = pattern.search(text, position)
        if not absolute:
            break
        anchors.append(absolute)
        position = absolute.end()
        expected += 1
    return anchors


def sequential_inline_anchors(text: str, maximum: int = 30) -> list[re.Match]:
    anchors: list[re.Match] = []
    position = 0
    expected = 1
    while expected <= maximum:
        pattern = re.compile(rf"(?<!\d){expected}\.\s*")
        match = pattern.search(text, position)
        if not match:
            break
        anchors.append(match)
        position = match.end()
        expected += 1
    return anchors


def parse_rc36_answers(text: str) -> dict[int, dict[int, str]]:
    answer_start = re.search(r"答\s+案", text)
    if not answer_start:
        return {}
    answer_text = text[answer_start.end() :]
    exercises = split_numbered_sections(answer_text, re.compile(r"(?im)^\s*Exe\s+(\d+)\s*$"))
    result: dict[int, dict[int, str]] = {}
    for exercise, block in exercises.items():
        values: dict[int, str] = {}
        for marker in re.finditer(r"(?<!\d)(1[0-3]|[1-9])\.\s*", block):
            number = int(marker.group(1))
            match = re.match(r"\s*([A-E](?:\s*[A-E]){0,2})(?=\s|\.|$)", block[marker.end() :])
            if not match:
                continue
            letters = "".join(re.findall(r"[A-E]", match.group(1)))
            if 1 <= len(letters) <= 3:
                values[number] = letters
        result[exercise] = values
    return result


def parse_rc36_explanations(text: str) -> dict[tuple[int, int], str]:
    exercises = split_numbered_sections(text, re.compile(r"(?im)^\s*EXERCISE\s*(\d+)\s*$"))
    explanations: dict[tuple[int, int], str] = {}
    for exercise, block in exercises.items():
        anchors = sequential_anchors(block, 13)
        for index, anchor in enumerate(anchors):
            end = anchors[index + 1].start() if index + 1 < len(anchors) else len(block)
            explanation = remove_layout_noise(block[anchor.end() : end])
            if explanation:
                explanations[(exercise, index + 1)] = explanation[:1600]
    return explanations


def import_rc36(question_text: str, solution_text: str, duplicates: DuplicateIndex) -> tuple[list[dict], dict]:
    answers = parse_rc36_answers(question_text)
    explanations = parse_rc36_explanations(solution_text)
    content_start = question_text.find("===== PDF PAGE 5 =====")
    content_end_match = re.search(r"答\s+案", question_text[content_start:])
    content_end = content_start + content_end_match.start() if content_end_match else len(question_text)
    content = question_text[content_start:content_end]
    exercises = split_numbered_sections(content, re.compile(r"(?im)^\s*Exercise\s+(\d+)\s*$"))
    imported: list[dict] = []
    detected = keyed = rejected = duplicate_count = 0
    for exercise in sorted(exercises):
        block = exercises[exercise]
        anchors = sequential_anchors(block, 13)
        detected += len(anchors)
        active_stimulus = clean_stimulus(block[: anchors[0].start()]) if anchors else ""
        for index, anchor in enumerate(anchors):
            number = index + 1
            end = anchors[index + 1].start() if index + 1 < len(anchors) else len(block)
            segment = block[anchor.end() : end]
            prompt, options, trailing = parse_options(segment, PAREN_OPTION)
            standalone_stimulus, prompt = split_standalone_prompt(prompt)
            answer = answers.get(exercise, {}).get(number)
            if trailing:
                candidate_stimulus = clean_stimulus(trailing)
            else:
                candidate_stimulus = ""
            if answer:
                keyed += 1
                difficulty = "easy" if exercise <= 12 else "medium" if exercise <= 28 else "hard"
                question = make_reading_question(
                    f"20260720p2-rc36-e{exercise:02d}-q{number:02d}",
                    difficulty,
                    standalone_stimulus or active_stimulus,
                    prompt,
                    options,
                    answer,
                    answer_explanation(answer, options, explanations.get((exercise, number), "")),
                    RC36_SOURCE,
                    f"Exercise {exercise} · Question {number} · PDF page {page_before(block, anchor.start())}",
                )
                if question is None:
                    rejected += 1
                elif duplicates.is_duplicate(question):
                    duplicate_count += 1
                else:
                    duplicates.add(question)
                    imported.append(question)
            if len(candidate_stimulus.split()) >= 18:
                active_stimulus = candidate_stimulus
    return imported, {
        "exercisesDetected": len(exercises),
        "questionBlocksDetected": detected,
        "letterKeysRecovered": keyed,
        "detailedExplanationsRecovered": len(explanations),
        "imported": len(imported),
        "duplicatesSkipped": duplicate_count,
        "rejectedIncompleteLayoutOrSentenceSelection": rejected,
    }


def read300_blocks(text: str) -> list[dict]:
    body_end = text.find("===== PDF PAGE 481 =====")
    body = text[:body_end if body_end >= 0 else len(text)]
    code_matches = list(re.finditer(r"【\s*(\d{5})\s*】", body))
    blocks = []
    previous = 0
    for code_index, code_match in enumerate(code_matches):
        raw = body[previous : code_match.start()]
        previous = code_match.end()
        candidates = list(re.finditer(r"(?m)^\s*(\d{1,3})\.\s+(.{8,140})\s*$", raw))
        heading = candidates[0] if code_index > 0 and candidates else None
        if code_index == 0:
            for candidate in reversed(candidates):
                title = normalized_space(candidate.group(2))
                after = remove_layout_noise(raw[candidate.end() : candidate.end() + 500])
                title_tokens = re.findall(r"[a-z]+", title.lower())[:5]
                after_tokens = re.findall(r"[a-z]+", after.lower())[:5]
                if len(title_tokens) >= 3 and title_tokens == after_tokens:
                    heading = candidate
                    break
        if not heading:
            continue
        passage_content = raw[heading.end() :]
        anchors = list(QUESTION_ANCHOR.finditer(passage_content))
        if not anchors:
            continue
        stimulus = clean_stimulus(passage_content[: anchors[0].start()])
        questions = []
        for index, anchor in enumerate(anchors):
            end = anchors[index + 1].start() if index + 1 < len(anchors) else len(passage_content)
            prompt, options, _ = parse_options(passage_content[anchor.end() : end], PLAIN_OPTION)
            # Restore prompt text captured on the anchor's line.
            prompt = clean_prompt(anchor.group(2) + " " + prompt)
            if contiguous_options(options):
                questions.append({"number": int(anchor.group(1)), "prompt": prompt, "options": options})
        blocks.append({
            "code": code_match.group(1),
            "ordinal": int(heading.group(1)),
            "title": normalized_space(heading.group(2)),
            "page": page_before(raw, heading.start()),
            "stimulus": stimulus,
            "questions": questions,
        })
    return blocks


def read300_answer_entries(text: str) -> list[tuple[str, str]]:
    start = text.find("===== PDF PAGE 481 =====")
    tail = text[start if start >= 0 else 0 :]
    entries: list[tuple[str, str]] = []
    for raw_line in tail.splitlines():
        line = normalized_space(raw_line)
        if not re.match(r"^\d+\s+", line):
            continue
        line = re.sub(r"^\d+\s+(?:\d+\.\s*)?", "", line)
        match = re.search(r"([A-E](?:\s*[A-E])*)$", line)
        if not match:
            continue
        title = normalized_space(line[: match.start()]).strip(" .")
        answer = "".join(re.findall(r"[A-E]", match.group(1)))
        if len(title.split()) >= 3 and answer:
            entries.append((title, answer))
    return entries


def partition_answers(questions: list[dict], letters: str) -> list[str] | None:
    solutions: list[list[str]] = []

    def visit(index: int, offset: int, current: list[str]) -> None:
        if len(solutions) > 2:
            return
        if index == len(questions):
            if offset == len(letters):
                solutions.append(current.copy())
            return
        option_count = len(questions[index]["options"])
        lengths = [1] if option_count == 5 else [1, 2, 3]
        for length in lengths:
            answer = letters[offset : offset + length]
            if len(answer) != length:
                continue
            allowed = set("ABCDE"[:option_count])
            if set(answer) <= allowed and len(set(answer)) == len(answer):
                visit(index + 1, offset + length, current + [answer])

    visit(0, 0, [])
    return solutions[0] if len(solutions) == 1 else None


def title_similarity(left: str, right: str) -> float:
    left_value = re.sub(r"[^a-z0-9]+", "", left.lower())[:100]
    right_value = re.sub(r"[^a-z0-9]+", "", right.lower())[:100]
    return difflib.SequenceMatcher(None, left_value, right_value).ratio()


def difficulty_for_read300(page: int) -> str:
    if page <= 22 or 93 <= page <= 146:
        return "easy"
    if page <= 57 or 147 <= page <= 390 or page >= 452:
        return "medium"
    return "hard"


def import_read300(text: str, duplicates: DuplicateIndex) -> tuple[list[dict], dict]:
    blocks = read300_blocks(text)
    answer_entries = read300_answer_entries(text)
    imported: list[dict] = []
    duplicate_count = rejected_key = rejected_layout = matched = 0
    match_scores: list[float] = []
    used_entries: set[int] = set()
    for block_index, block in enumerate(blocks, 1):
        best: tuple[float, int, str] | None = None
        for entry_index, (title, letters) in enumerate(answer_entries):
            if entry_index in used_entries:
                continue
            score = title_similarity(block["title"], title)
            if best is None or score > best[0]:
                best = (score, entry_index, letters)
        if best is None or best[0] < 0.72:
            rejected_key += len(block["questions"])
            continue
        answers = partition_answers(block["questions"], best[2])
        if answers is None:
            rejected_key += len(block["questions"])
            continue
        used_entries.add(best[1])
        matched += 1
        match_scores.append(best[0])
        for question_index, (parsed, answer) in enumerate(zip(block["questions"], answers), 1):
            explanation = answer_explanation(answer, parsed["options"])
            question = make_reading_question(
                f"20260720p2-read300-p{block_index:03d}-{block['code']}-q{parsed['number']:02d}",
                difficulty_for_read300(block["page"]),
                block["stimulus"],
                parsed["prompt"],
                parsed["options"],
                answer,
                explanation,
                READ300_SOURCE,
                f"Passage {block['ordinal']} · code {block['code']} · PDF page {block['page']}",
            )
            if question is None:
                rejected_layout += 1
            elif duplicates.is_duplicate(question):
                duplicate_count += 1
            else:
                duplicates.add(question)
                imported.append(question)
    return imported, {
        "codedPassagesDetected": len(blocks),
        "answerEntriesDetected": len(answer_entries),
        "passagesUniquelyMatched": matched,
        "questionBlocksDetected": sum(len(block["questions"]) for block in blocks),
        "imported": len(imported),
        "duplicatesSkipped": duplicate_count,
        "rejectedAmbiguousAnswerSequence": rejected_key,
        "rejectedIncompleteLayout": rejected_layout,
        "lowestAcceptedTitleMatch": round(min(match_scores), 4) if match_scores else None,
    }


def test_answer_sections(test_block: str, test_number: int) -> dict[int, list[str]]:
    marker = re.search(rf"ANSWER KEY FOR PRACTICE TEST\s*{test_number}", test_block, re.I)
    if not marker:
        return {}
    key_text = test_block[marker.end() :]
    scoring = re.search(r"SCORING THE GRE PRACTICE TEST", key_text, re.I)
    if scoring:
        key_text = key_text[: scoring.start()]
    sections = split_numbered_sections(key_text, re.compile(r"(?im)^\s*Section\s+(\d+):\s*(?:Verbal|Quantitative)\s+Reasoning\s*$"))
    result: dict[int, list[str]] = {}
    for section, block in sections.items():
        block = block.split("Number of correct answers", 1)[0]
        tokens = re.findall(r"(?m)^\s*([A-I](?:\s*,\s*[A-I])*)\s*$", block)
        result[section] = ["".join(re.findall(r"[A-I]", token)) for token in tokens]
    return result


def gruber_question_anchors(text: str) -> list[re.Match]:
    starts = list(re.finditer(r"(?m)^\s*1\.\s*(?!\d)", text))
    best: list[re.Match] = []
    best_score = (-1, -1)
    for start in starts:
        anchors = [start]
        position = start.end()
        for number in range(2, 26):
            match = re.compile(rf"(?m)^\s*{number}\.\s*(?!\d)").search(text, position)
            if not match:
                break
            anchors.append(match)
            position = match.end()
        substantive_gaps = sum(
            anchors[index + 1].start() - anchors[index].end() >= 20
            for index in range(len(anchors) - 1)
        )
        score = (len(anchors), substantive_gaps)
        if score > best_score:
            best = anchors
            best_score = score
    return best


def make_gruber_completion(
    test_number: int,
    section: int,
    number: int,
    raw: str,
    answer: str,
) -> dict | None:
    raw = PAGE_MARKER.sub(" ", raw)
    raw = re.sub(r"(?im)^\s*(?:STOP!|Do not turn.*|SECTION \d+:.*)$", " ", raw)
    blank_matches = list(re.finditer(r"(?im)^\s*Blank\s+(\d+)\s*$", raw))
    groups = []
    correct: dict[str, list[str]] = {}
    if blank_matches:
        prompt = clean_prompt(raw[: blank_matches[0].start()])
        if len(blank_matches) != len(answer):
            return None
        for index, blank in enumerate(blank_matches):
            end = blank_matches[index + 1].start() if index + 1 < len(blank_matches) else len(raw)
            choices = [normalized_space(line) for line in raw[blank.end() : end].splitlines() if normalized_space(line)]
            choices = [choice for choice in choices if not PAGE_MARKER.fullmatch(choice)]
            if len(choices) > 3 and choices[3].lower().startswith("directions"):
                choices = choices[:3]
            if len(choices) != 3 or any(len(choice) > 100 for choice in choices):
                return None
            group_id = f"blank{index + 1}"
            groups.append({
                "id": group_id,
                "title": f"Blank ({['i', 'ii', 'iii'][index]})",
                "options": [{"id": f"o{choice_index}", "text": choice} for choice_index, choice in enumerate(choices)],
                "maximumSelections": 1,
            })
            global_index = ord(answer[index]) - ord("A")
            local_index = global_index - index * 3
            if not 0 <= local_index < 3:
                return None
            correct[group_id] = [f"o{local_index}"]
    else:
        lines = [normalized_space(line) for line in raw.splitlines() if normalized_space(line)]
        if len(lines) < 7 or len(answer) != 1 or answer not in "ABCDE":
            return None
        choices = lines[-5:]
        prompt = normalized_space(" ".join(lines[:-5]))
        if any(len(choice) > 100 for choice in choices):
            return None
        groups = [{
            "id": "blank1",
            "title": "Blank (i)",
            "options": [{"id": f"o{index}", "text": choice} for index, choice in enumerate(choices)],
            "maximumSelections": 1,
        }]
        correct = {"blank1": [f"o{ord(answer) - ord('A')}"]}
    prompt = re.sub(r"_{4,}", "______", prompt)
    if "______" not in prompt or len(prompt.split()) < 6:
        return None
    selected = []
    for group in groups:
        chosen = correct[group["id"]][0]
        selected.append(group["options"][int(chosen[1:])]["text"])
    explanation = "正確填入「" + "」、「".join(selected) + "」。將各詞依序代入後，句子的文法、轉折、因果與語氣關係一致。"
    return {
        "id": f"20260720p2-gruber-t{test_number}-s{section}-q{number:02d}",
        "measure": "verbal",
        "difficulty": ["easy", "medium", "hard"][(test_number + section + number) % 3],
        "format": "textCompletion",
        "stimulus": None,
        "prompt": prompt,
        "quantityA": None,
        "quantityB": None,
        "groups": groups,
        "correctSelections": correct,
        "acceptedNumericAnswers": [],
        "explanation": explanation,
        "contentArea": "Text Completion",
        "source": {
            "title": GRUBER_QUESTION_SOURCE,
            "detail": f"Practice Test {test_number} · Verbal Section {section} · Question {number}",
            "isAuthorizedSourceItem": True,
        },
    }


def extract_gruber_completion_layouts(pdf_path: Path) -> dict[tuple[int, int], str]:
    starts = {
        (1, 1): 1624,
        (1, 2): 1639,
        (2, 1): 1775,
        (2, 2): 1789,
        (3, 1): 1925,
        (3, 2): 1939,
    }
    layouts: dict[tuple[int, int], str] = {}
    with pdfplumber.open(pdf_path) as document:
        for key, first_page in starts.items():
            pages = []
            for page_number in range(first_page, first_page + 6):
                page_text = document.pages[page_number - 1].extract_text(layout=True) or ""
                pages.append(f"===== PDF PAGE {page_number} =====\n{page_text}")
            layouts[key] = "\n".join(pages)
    return layouts


def import_gruber(
    text: str,
    completion_layouts: dict[tuple[int, int], str],
    duplicates: DuplicateIndex,
) -> tuple[list[dict], dict]:
    start = text.rfind("Three GRE Practice Tests")
    region = text[start if start >= 0 else 0 :]
    test_matches = list(re.finditer(r"(?im)^\s*GRE PRACTICE TEST\s*\n\s*([123])\s*$", region))
    imported: list[dict] = []
    detected = keyed = rejected = duplicate_count = 0
    for test_index, match in enumerate(test_matches):
        test_number = int(match.group(1))
        end = test_matches[test_index + 1].start() if test_index + 1 < len(test_matches) else len(region)
        test_block = region[match.end() : end]
        answers = test_answer_sections(test_block, test_number)
        for section in [1, 2]:
            section_block = completion_layouts.get((test_number, section), "")
            anchors = gruber_question_anchors(section_block)
            detected += min(8, len(anchors))
            section_answers = answers.get(section, [])
            for number in range(1, min(8, len(anchors)) + 1):
                if number > len(section_answers):
                    rejected += 1
                    continue
                keyed += 1
                anchor = anchors[number - 1]
                question_end = anchors[number].start() if number < len(anchors) else len(section_block)
                question = make_gruber_completion(
                    test_number,
                    section,
                    number,
                    section_block[anchor.end() : question_end],
                    section_answers[number - 1],
                )
                if question is None:
                    rejected += 1
                elif duplicates.is_duplicate(question):
                    duplicate_count += 1
                else:
                    duplicates.add(question)
                    imported.append(question)

    issue_prompts = []
    for match in re.finditer(r"(?is)ANALYTICAL WRITING 1: ANALYZE AN ISSUE.*?\nIssue\s*\n(.+?)\nUse this page", region):
        prompt = normalized_space(match.group(1))
        if 8 <= len(prompt.split()) <= 80 and prompt not in issue_prompts:
            issue_prompts.append(prompt)
    for index, prompt in enumerate(issue_prompts, 1):
        question = {
            "id": f"20260720p2-gruber-issue-{index:02d}",
            "measure": "analyticalWriting",
            "difficulty": "medium",
            "format": "essay",
            "stimulus": None,
            "prompt": prompt,
            "quantityA": None,
            "quantityB": None,
            "groups": [],
            "correctSelections": {},
            "acceptedNumericAnswers": [],
            "explanation": "請提出明確立場，以具體理由與例證支援論點，並處理可能的限制、反例或相反觀點。",
            "contentArea": "Analyze an Issue",
            "source": {
                "title": GRUBER_QUESTION_SOURCE,
                "detail": f"Practice Test {index} · Analyze an Issue",
                "isAuthorizedSourceItem": True,
            },
        }
        if not duplicates.is_duplicate(question):
            duplicates.add(question)
            imported.append(question)
    return imported, {
        "practiceTestsDetected": len(test_matches),
        "textCompletionBlocksDetected": detected,
        "answerKeysRecovered": keyed,
        "issuePromptsRecovered": len(issue_prompts),
        "imported": len(imported),
        "duplicatesSkipped": duplicate_count,
        "rejectedIncompleteLayout": rejected,
        "excludedByPolicy": "Reading and Quant layouts that cannot be paired deterministically, obsolete Analyze-an-Argument tasks, analogies, and antonyms remain audit-only.",
    }


def parse_gruber_vocabulary(text: str) -> list[tuple[str, str]]:
    start = text.find("THE GRUBER GRE 3,400-WORD LIST")
    end = text.find("VOCABULARY\nThis vocabulary section", start)
    if start < 0 or end < 0:
        return []
    block = text[start:end]
    records: dict[str, tuple[str, str]] = {}
    for match in re.finditer(r"(?m)^([^\n]+)\n\u2003(.*?)(?=^[^\n]+\n\u2003|\Z)", block, re.S):
        word = normalized_space(match.group(1)).replace("’", "'")
        definition = match.group(2).split("===== PDF PAGE", 1)[0]
        definition = re.sub(r"\((?:noun|verb|adjective|adverb)\)", "", definition, flags=re.I)
        definition = normalized_space(definition)
        if not re.fullmatch(r"[A-Za-z][A-Za-z' .-]{0,45}", word):
            continue
        if not definition or len(definition) > 500:
            continue
        records.setdefault(normalized_word(word), (word, definition))
    return [records[key] for key in sorted(records)]


def merged_existing_vocabulary() -> dict[str, dict]:
    merged: dict[str, dict] = {}
    for name in ["ExpandedVocabulary.json", "Authorized20260720Vocabulary.json"]:
        for item in read_json(RESOURCES / name):
            key = normalized_word(item["word"])
            if key not in merged:
                merged[key] = copy.deepcopy(item)
            else:
                current = merged[key]
                for field in ["pronunciation", "definition", "chinese", "example", "exampleSource", "exampleSourceURL"]:
                    if not current.get(field) and item.get(field):
                        current[field] = item[field]
                current["synonyms"] = sorted(set(current.get("synonyms", []) + item.get("synonyms", [])))
                current["sources"] = sorted(set(current.get("sources", []) + item.get("sources", [])))
                current["isHighFrequency"] = current.get("isHighFrequency", False) or item.get("isHighFrequency", False)
    return merged


def import_gruber_vocabulary(
    text: str,
    ecdict_path: Path,
    tatoeba_cc0: Path,
    tatoeba_english: Path,
) -> tuple[list[dict], dict]:
    parsed = parse_gruber_vocabulary(text)
    existing = merged_existing_vocabulary()
    new_keys = {normalized_word(word) for word, _ in parsed if normalized_word(word) not in existing}
    dictionary = {
        key: value
        for key, value in load_ecdict(ecdict_path, new_keys).items()
        if compact_translation(value.translation)
    }
    output: list[dict] = []
    overlap = new_supported = unsupported = 0
    for word, definition in parsed:
        key = normalized_word(word)
        if key in existing:
            entry = copy.deepcopy(existing[key])
            overlap += 1
        elif key in dictionary:
            entry = {
                "word": word,
                "pronunciation": "",
                "definition": definition,
                "chinese": "",
                "synonyms": [],
                "example": "",
                "sources": [],
                "isHighFrequency": True,
            }
            new_supported += 1
        else:
            unsupported += 1
            continue
        sources = set(entry.get("sources", []))
        sources.add(GRUBER_VOCAB_SOURCE)
        entry["sources"] = sorted(sources)
        entry["isHighFrequency"] = True
        output.append(entry)

    enrichment = enrich_vocabulary_entries(
        output,
        ecdict_path,
        tatoeba_cc0,
        tatoeba_english,
        refresh_invalid_examples=True,
    )
    for entry in output:
        entry["chinese"] = taiwan_text(entry.get("chinese", ""))
        if not entry["chinese"] or not entry.get("example", "").strip():
            raise ValueError(f"Incomplete vocabulary record: {entry['word']}")
        if not re.search(
            rf"(?<![A-Za-z]){re.escape(entry['word'])}(?![A-Za-z])",
            entry["example"],
            re.I,
        ):
            raise ValueError(f"Example does not use headword: {entry['word']}")
        if TAIWAN.convert(entry["chinese"]) != entry["chinese"]:
            raise ValueError(f"Non-Taiwan Chinese remains in {entry['word']}")
    return output, {
        "listEntriesDetected": len(parsed),
        "existingWordsSourceMerged": overlap,
        "newWordsImported": new_supported,
        "rejectedWithoutECDICTChineseDefinition": unsupported,
        "completeRecordsWritten": len(output),
        "enrichment": enrichment,
    }


def validate_questions(questions: list[dict]) -> None:
    ids = [question["id"] for question in questions]
    if len(ids) != len(set(ids)):
        raise ValueError("Part-two question IDs are not unique")
    signatures = [content_signature(question) for question in questions]
    if len(signatures) != len(set(signatures)):
        raise ValueError("Part-two question content is not unique")
    for question in questions:
        if not question["prompt"].strip() or not question["explanation"].strip():
            raise ValueError(f"Incomplete question text: {question['id']}")
        visible_fields = [question.get("stimulus") or "", question["prompt"]]
        visible_fields.extend(
            option["text"] for group in question["groups"] for option in group["options"]
        )
        if any(SELECT_ALL_INSTRUCTION.search(value) or LAYOUT_NOISE.search(value) for value in visible_fields):
            raise ValueError(f"Layout instruction remains in {question['id']}")
        if TAIWAN.convert(question["explanation"]) != question["explanation"]:
            raise ValueError(f"Simplified Chinese remains in {question['id']}")
        if question["format"] == "essay":
            continue
        option_ids = {option["id"] for group in question["groups"] for option in group["options"]}
        correct_ids = {value for values in question["correctSelections"].values() for value in values}
        if not correct_ids or not correct_ids <= option_ids:
            raise ValueError(f"Invalid answer key: {question['id']}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--extracted-dir", type=Path, required=True)
    parser.add_argument("--ecdict", type=Path, required=True)
    parser.add_argument("--tatoeba-cc0", type=Path, required=True)
    parser.add_argument("--tatoeba-english", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=RESOURCES)
    args = parser.parse_args()

    existing_questions = []
    for name in ["ExpandedQuestions.json", "Authorized20260720Questions.json", "BalancedQuantQuestions.json"]:
        existing_questions.extend(read_json(RESOURCES / name))
    duplicates = DuplicateIndex(existing_questions)

    rc36_text = (args.extracted_dir / "新GRE阅读理解36套 GRE-RC-36 2012-01版.txt").read_text(encoding="utf-8")
    rc36_solution = (args.extracted_dir / "新GRE阅读36套解析.txt").read_text(encoding="utf-8")
    read300_text = (args.extracted_dir / "GRE阅读300篇.txt").read_text(encoding="utf-8")
    gruber_text = (args.extracted_dir / "Grubers complete GRE guide.txt").read_text(encoding="utf-8")

    questions: list[dict] = []
    rc36_questions, rc36_audit = import_rc36(rc36_text, rc36_solution, duplicates)
    questions.extend(rc36_questions)
    read300_questions, read300_audit = import_read300(read300_text, duplicates)
    questions.extend(read300_questions)
    gruber_layouts = extract_gruber_completion_layouts(args.source_dir / "Grubers complete GRE guide.pdf")
    gruber_questions, gruber_audit = import_gruber(gruber_text, gruber_layouts, duplicates)
    questions.extend(gruber_questions)
    validate_questions(questions)

    vocabulary, vocabulary_audit = import_gruber_vocabulary(
        gruber_text,
        args.ecdict,
        args.tatoeba_cc0,
        args.tatoeba_english,
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    write_json(args.output_dir / "Authorized20260720Part2Questions.json", questions)
    write_json(args.output_dir / "Authorized20260720Part2Vocabulary.json", vocabulary)
    manifest = {
        "questionCount": len(questions),
        "questionCountsByMeasure": dict(sorted(Counter(question["measure"] for question in questions).items())),
        "questionCountsByFormat": dict(sorted(Counter(question["format"] for question in questions).items())),
        "questionAudit": {
            "reading36Sets": rc36_audit,
            "reading300Passages": read300_audit,
            "gruberGuide": gruber_audit,
        },
        "vocabularyCount": len(vocabulary),
        "vocabularyAudit": vocabulary_audit,
        "sourceInventory": {
            "pdfFiles": len(list(args.source_dir.rglob("*.pdf"))),
            "reading36QuestionPDF": "Text-identical after normalization to the previously audited 36-set question PDF; the newly supplied per-set analyses improve answer and explanation cross-checking.",
            "reading36SupplementalAnalyses": len(list((args.source_dir / "網友翻譯解析").glob("*.pdf"))),
            "policy": "Only items with complete text, choices, and deterministic answer alignment are emitted. Duplicate and obsolete formats remain audit-only.",
        },
        "languagePolicy": "All bundled Chinese fields are converted with OpenCC s2twp and checked for idempotence; every emitted vocabulary record has a Taiwan Traditional Chinese definition and an English example that uses its headword.",
    }
    write_json(args.output_dir / "Authorized20260720Part2Manifest.json", manifest)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
